version: "3"
services:
  # elasticsearch + kibana exist in AWS.
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    environment:
      - 'ELASTICSEARCH_URL=http://elasticsearch:9200'
      - 'LOGSPOUT=ignore'
    ports:
      - 5601:5601
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - 'discovery.type=single-node'
      - 'LOGSPOUT=ignore'
    ports:
      - 9200:9200
      - 9300:9300
  # these two can be run in daemon mode on ECS
  logspout:
    image: local/logspout-logstash
    restart: on-failure
    environment:
      - 'LOGSPOUT=ignore'
      - 'ROUTE_URIS=logstash://logstash:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    environment:
      - 'LOGSPOUT=ignore'
    volumes:
      - ./logstash/:/usr/share/logstash/pipeline/
