version: "3"
services:
  # these two can be run in daemon mode on ECS
  logspout:
    image: local/logspout-logstash
    restart: on-failure
    environment:
      - 'LOGSPOUT=ignore'
      - 'ROUTE_URIS=logstash://logstash:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    environment:
      - 'LOGSPOUT=ignore'
    volumes:
      - ./logstash/:/usr/share/logstash/pipeline/
      # this config needs to change too
      - ./logstash/yml/logstash.yml:/usr/share/logstash/config/logstash.yml
